apiVersion: v1
kind: ConfigMap
metadata:
  name: ginflix-config
  namespace: ginflix
data:
  BACKEND_URL: "https://ginflix27.gin-telecom.ovh"
  STREAM_URL: "https://ginflix27.gin-telecom.ovh"
  KEYCLOAK_CLIENT_ID: "ginflix27"
  KEYCLOAK_REALM: "ginflix"
  KEYCLOAK_HOST: "idp.gin-telecom.ovh"
  GARAGE_ENDPOINT: "s3.gin-telecom.ovh"
  MONGO_URI: "mongodb://mongodb-service:27017/ginflix"
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: ginflix
type: Opaque
stringData:
  bucket: ginflix27
  access-key: GKd1483513d0198e34f5271493
  secret-key: 3be0d8cea2217a952b6945751bf3d45f7b228bae8df75dacad92b8120234570a
  endpoint: s3.gin-telecom.ovh
