- name: Installer NGINX
  apt:
    name:
      - nginx
    update_cache: yes

- name: install certbot
  community.general.snap:
    name:
      - certbot
    classic: true

- name: set certbot privilege
  ansible.builtin.command: snap set certbot trust-plugin-with-root=ok

- name: install certbot addons
  community.general.snap:
    name:
      - certbot-dns-route53
    classic: true

- name: issue certificate
  ansible.builtin.command: certbot --non-interactive --redirect --agree-tos --nginx -d {{domain}} -m {{email}} 

- name: Supprimer le lien symbolique default dans sites-enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copier mon-site.conf
  copy:
    src: loadbalancer.conf
    dest: /etc/nginx/sites-enabled/mon-site.conf  
    mode: '0644'


- name: Restart NGINX
  service:
    name: nginx
    state: restarted